[phases.setup]
nixPkgs = [
  "python39",
  "gcc",
  "ffmpeg",
  "mesa.drivers",
  "libglvnd",
  "glib",
  "cairo",
  "stdenv.cc.cc.lib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXi",
  "xorg.libXrender"
]

[phases.install]
cmd = """
  pip install --no-cache-dir -r requirements.txt && \
  rm -rf /root/.cache/pip && \
  find /usr/local/lib/python*/site-packages -name "*.so" | xargs strip -s
"""

[phases.start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"