[phases.setup]
nixPkgs = [
  "python39",
  "gcc",
  "ffmpeg",
  "libGL",
  "mesa"
]

[phases.install]
cmd = """
  pip install --no-deps opencv-python-headless==4.7.0.72 && \
  pip install -r requirements.txt && \
  rm -rf /usr/local/lib/python*/site-packages/cv2/data/haarcascades
"""

[phases.start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"